name: Add Read Time Badge
on:
  push:
    paths:
    - 'readme.md'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
    steps:
    - name: setup node
      uses: actions/setup-node@v2
    - uses: actions/checkout@2
      with: 
        path: 'repo'
    - name: Get Github-read-time-badge package
      run: |
        npm i -g github-read-time-badge
        x=$(find repo -maxdepth 1 -iname readme.md)
        read-time-badge $x

