name: Add Read Time Badge
on:
  push:
    paths:
    - 'README.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: '12'
    - uses: actions/checkout@v2
      with: 
        path: 'repo'
    - name: Get Github-read-time-badge package
      run: |
        npm i -g github-read-time-badge
        x=$(find repo -maxdepth 1 -iname readme.md)
        read-time-badge $x
        cd repo
        git config --global user.name 'Github Read Time Badge [Bot]'
        git config --global user.email 'joshua-rose@users.noreply.github.com'
        git commit -am "Added/Updated Badge"
        git push
        cd ..
        rm -fr repo
        exit

